# Generated by Django 4.1.7 on 2023-04-10 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistCont', '0013_alter_auxiliar_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliar',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SistCont.tipocuenta'),
        ),
    ]
