# Generated by Django 4.1.7 on 2023-04-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistCont', '0014_alter_auxiliar_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxiliar',
            name='id_EC',
            field=models.CharField(default='EC1', max_length=10, unique=True),
        ),
    ]
