# Generated by Django 4.1.7 on 2023-04-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistCont', '0015_auxiliar_id_ec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogoauxiliares',
            name='id_EC',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
