# Generated by Django 4.1.7 on 2023-04-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistCont', '0016_alter_catalogoauxiliares_id_ec'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxiliar',
            name='transferido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auxiliar',
            name='id_EC',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
