# Generated by Django 4.1.7 on 2023-04-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistCont', '0017_auxiliar_transferido_alter_auxiliar_id_ec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliar',
            name='transferido',
            field=models.BooleanField(default=False),
        ),
    ]
