# Generated by Django 4.1.7 on 2023-04-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistCont', '0020_tipomoneda_codigo_iso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomoneda',
            name='ultima_tasa_cambiaria',
            field=models.FloatField(blank=True),
        ),
    ]
